"""
Generate Vedic graha-in-rashi rules (84 = 7 grahas × 12 rashis).
Sources: Narasimha Rao, Agarwal Vedic Astrology Vol.2-3, BPHS tradition.
"""
import json, os

BASE       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FILE   = os.path.join(BASE, 'generator', 'rules', 'vedic-rashi-rules.json')
NODES_FILE = os.path.join(BASE, 'data', 'knowledge-graph', 'nodes.jsonl')

existing_nodes = set()
for line in open(NODES_FILE, encoding='utf-8'):
    if line.strip():
        existing_nodes.add(json.loads(line)['id'])

# ── Rashi data ────────────────────────────────────────────────────────────────
RASHIS = [
    ("Mesha",      "Овен",      "Mars",   "fire",  "cardinal",
     "initiative, courage, self-assertion, and new beginnings",
     "инициатива, смелость, самоутверждение и новые начинания"),
    ("Vrishabha",  "Телец",     "Venus",  "earth", "fixed",
     "stability, sensory experience, material values, and endurance",
     "стабильность, чувственный опыт, материальные ценности и стойкость"),
    ("Mithuna",    "Близнецы",  "Mercury","air",   "mutable",
     "communication, adaptability, intellectual curiosity, and duality",
     "коммуникация, адаптивность, интеллектуальное любопытство и двойственность"),
    ("Karka",      "Рак",       "Moon",   "water", "cardinal",
     "nurturing, emotional sensitivity, home, roots, and inner security",
     "забота, эмоциональная чуткость, дом, корни и внутренняя безопасность"),
    ("Simha",      "Лев",       "Sun",    "fire",  "fixed",
     "self-expression, leadership, creative power, dignity, and recognition",
     "самовыражение, лидерство, творческая сила, достоинство и признание"),
    ("Kanya",      "Дева",      "Mercury","earth", "mutable",
     "discernment, service, purification, analytical skill, and refinement",
     "различение, служение, очищение, аналитические способности и совершенствование"),
    ("Tula",       "Весы",      "Venus",  "air",   "cardinal",
     "balance, relationship, justice, aesthetic sense, and diplomacy",
     "равновесие, отношения, справедливость, эстетическое чувство и дипломатия"),
    ("Vrishchika", "Скорпион",  "Mars",   "water", "fixed",
     "transformation, depth, hidden power, intensity, and regeneration",
     "трансформация, глубина, скрытая сила, интенсивность и возрождение"),
    ("Dhanu",      "Стрелец",   "Jupiter","fire",  "mutable",
     "wisdom, expansion, higher truth, philosophy, and spiritual aspiration",
     "мудрость, расширение, высшая истина, философия и духовное устремление"),
    ("Makara",     "Козерог",   "Saturn", "earth", "cardinal",
     "ambition, discipline, worldly achievement, structure, and perseverance",
     "амбиции, дисциплина, мирские достижения, структура и настойчивость"),
    ("Kumbha",     "Водолей",   "Saturn", "air",   "fixed",
     "universality, social vision, individuality, innovation, and detachment",
     "универсальность, социальное видение, индивидуальность, инновации и отстранённость"),
    ("Meena",      "Рыбы",      "Jupiter","water", "mutable",
     "compassion, surrender, spiritual sensitivity, dissolution, and unity",
     "сострадание, растворение, духовная чуткость, самоотдача и единство"),
]

# ── Graha data ────────────────────────────────────────────────────────────────
GRAHAS = {
    "Sun": {
        "ru": "Сурья",
        "nature": "solar, kingly, royal, authoritative",
        "nature_ru": "солнечная, царственная, властная, авторитетная",
        "exalt": "Mesha", "debil": "Tula", "own": ["Simha"],
        "friends": ["Moon","Mars","Jupiter"], "enemies": ["Saturn","Venus"],
        "principle_en": "the soul, identity, will, father, authority, and life-force",
        "principle_ru": "душа, идентичность, воля, отец, авторитет и жизненная сила",
    },
    "Moon": {
        "ru": "Чандра",
        "nature": "lunar, receptive, nurturing, reflective",
        "nature_ru": "лунная, восприимчивая, питающая, отражающая",
        "exalt": "Vrishabha", "debil": "Vrishchika", "own": ["Karka"],
        "friends": ["Sun","Mercury"], "enemies": ["Saturn"],
        "principle_en": "the mind, emotions, mother, instincts, and nourishment",
        "principle_ru": "ум, эмоции, мать, инстинкты и питание",
    },
    "Mars": {
        "ru": "Мангал",
        "nature": "fiery, martial, energetic, assertive",
        "nature_ru": "огненная, воинственная, энергичная, напористая",
        "exalt": "Makara", "debil": "Karka", "own": ["Mesha","Vrishchika"],
        "friends": ["Sun","Moon","Jupiter"], "enemies": ["Mercury"],
        "principle_en": "energy, courage, action, desire, and the capacity for effort",
        "principle_ru": "энергия, смелость, действие, желание и способность к усилию",
    },
    "Mercury": {
        "ru": "Будха",
        "nature": "intellectual, mercurial, adaptable, analytical",
        "nature_ru": "интеллектуальная, меркурианская, адаптивная, аналитическая",
        "exalt": "Kanya", "debil": "Meena", "own": ["Mithuna","Kanya"],
        "friends": ["Sun","Venus"], "enemies": ["Moon"],
        "principle_en": "intellect, speech, commerce, discrimination, and skill",
        "principle_ru": "интеллект, речь, торговля, различение и умение",
    },
    "Jupiter": {
        "ru": "Гуру",
        "nature": "expansive, wise, benevolent, spiritual",
        "nature_ru": "расширяющаяся, мудрая, благожелательная, духовная",
        "exalt": "Karka", "debil": "Makara", "own": ["Dhanu","Meena"],
        "friends": ["Sun","Moon","Mars"], "enemies": ["Mercury","Venus"],
        "principle_en": "wisdom, dharma, guru, children, grace, and expansion",
        "principle_ru": "мудрость, дхарма, учитель, дети, благодать и расширение",
    },
    "Venus": {
        "ru": "Шукра",
        "nature": "harmonious, pleasurable, aesthetic, relational",
        "nature_ru": "гармоничная, чувственная, эстетическая, реляционная",
        "exalt": "Meena", "debil": "Kanya", "own": ["Vrishabha","Tula"],
        "friends": ["Mercury","Saturn"], "enemies": ["Sun","Moon"],
        "principle_en": "beauty, love, desire, luxury, artistic sense, and relationship",
        "principle_ru": "красота, любовь, желание, роскошь, художественное чувство и отношения",
    },
    "Saturn": {
        "ru": "Шани",
        "nature": "austere, disciplining, karmic, slow",
        "nature_ru": "аскетическая, дисциплинирующая, кармическая, медленная",
        "exalt": "Tula", "debil": "Mesha", "own": ["Makara","Kumbha"],
        "friends": ["Mercury","Venus"], "enemies": ["Sun","Moon","Mars"],
        "principle_en": "karma, discipline, limitation, longevity, service, and renunciation",
        "principle_ru": "карма, дисциплина, ограничение, долголетие, служение и отречение",
    },
}

# ── Dignity relationship ───────────────────────────────────────────────────────
def dignity(graha_key, rashi_name, gd):
    if rashi_name == gd["exalt"]:    return ("exalted",   "в экзальтации")
    if rashi_name == gd["debil"]:    return ("debilitated","в падении")
    if rashi_name in gd["own"]:      return ("own sign",  "в собственном знаке")
    rashi_ruler = next(r[2] for r in RASHIS if r[0] == rashi_name)
    if rashi_ruler in gd["friends"]: return ("friendly",  "в дружественном знаке")
    if rashi_ruler in gd["enemies"]: return ("inimical",  "во враждебном знаке")
    return ("neutral", "в нейтральном знаке")

# ── Per-combination interpretations ───────────────────────────────────────────
# Each entry: (summary_en, summary_ru, pattern_en, pattern_ru, growth_en, growth_ru)
INTERP = {
# ── SUN ───────────────────────────────────────────────────────────────────────
("Sun","Mesha"):     ("Sun in Mesha is exalted: the soul-principle is strong, direct, and confident — a natural pioneer energy.",
                      "Сурья в Меша (экзальтация): принцип души силён, прям и уверен — природная энергия первопроходца.",
                      "The will expresses itself decisively. Leadership comes naturally but may tip into impulsiveness or arrogance.",
                      "Воля выражается решительно. Лидерство приходит естественно, но может переходить в импульсивность или высокомерие.",
                      "Channel the drive for self-assertion into purposeful initiative rather than reactive dominance.",
                      "Направить стремление к самоутверждению в целенаправленную инициативу, а не в реактивное доминирование."),
("Sun","Vrishabha"): ("Sun in Vrishabha: the soul-principle steadies itself through material form, sensory beauty, and quiet endurance.",
                      "Сурья в Вришабха: принцип души укрепляется через материальную форму, чувственную красоту и тихую стойкость.",
                      "Identity is linked to what is owned, created, or cultivated. There is a strong sense of worth and aesthetic sensibility.",
                      "Идентичность связана с тем, чем владеют, что создают или возделывают. Сильное чувство собственной ценности и эстетическое чутьё.",
                      "Cultivate flexibility alongside stability — the soul grows when it can let go as well as hold.",
                      "Культивировать гибкость наряду со стабильностью — душа растёт, когда умеет отпускать так же, как удерживать."),
("Sun","Mithuna"):   ("Sun in Mithuna: the soul-principle expresses itself through ideas, words, and intellectual variety.",
                      "Сурья в Митхуна: принцип души выражает себя через идеи, слова и интеллектуальное разнообразие.",
                      "The mind is quick and the identity is fluid. There is a gift for communication but a risk of scattered self-expression.",
                      "Ум быстрый, идентичность гибкая. Дар к коммуникации, но риск рассредоточенного самовыражения.",
                      "Develop depth alongside breadth — commit to one current of self-expression rather than perpetually sampling.",
                      "Развивать глубину наряду с широтой — посвятить себя одному потоку самовыражения, а не бесконечно пробовать разные."),
("Sun","Karka"):     ("Sun in Karka: the soul-principle seeks expression through emotional connection, care, and inner life.",
                      "Сурья в Карка: принцип души ищет выражения через эмоциональные связи, заботу и внутреннюю жизнь.",
                      "Identity is shaped by family, home, and belonging. Authority is experienced through nurturing roles.",
                      "Идентичность формируется семьёй, домом и чувством принадлежности. Авторитет переживается через роль кормильца.",
                      "Distinguish between emotional security-seeking and genuine self-expression — the soul is not only a protector but a creator.",
                      "Различать поиск эмоциональной безопасности и подлинное самовыражение — душа не только защитник, но и творец."),
("Sun","Simha"):     ("Sun in Simha is in its own sign: the soul-principle is at home — dignified, radiant, and creatively alive.",
                      "Сурья в Симха (своя обитель): принцип души у себя дома — достойный, лучезарный и творчески живой.",
                      "Self-expression is natural and magnetic. There is a strong need for recognition and a gift for leadership.",
                      "Самовыражение естественно и магнетично. Сильная потребность в признании и дар к лидерству.",
                      "Balance genuine self-radiance with openness to others — the heart shines brightest when it also illuminates those around it.",
                      "Уравновешивать подлинное самосияние с открытостью к другим — сердце светит ярче всего, когда освещает и тех, кто рядом."),
("Sun","Kanya"):     ("Sun in Kanya: the soul-principle serves through discernment, analysis, and careful refinement.",
                      "Сурья в Канья: принцип души служит через различение, анализ и тщательное совершенствование.",
                      "Identity is expressed through work and precision. There is a risk of over-criticism directed at self or others.",
                      "Идентичность выражается через работу и точность. Риск чрезмерной самокритики или критики других.",
                      "Use the power of discernment to build rather than to diminish — serve the vision, not the fear of imperfection.",
                      "Использовать силу различения для созидания, а не умаления — служить видению, а не страху несовершенства."),
("Sun","Tula"):      ("Sun in Tula is debilitated: the soul-principle struggles to assert itself clearly — it defers, deliberates, and seeks external validation.",
                      "Сурья в Тула (падение): принцип души с трудом утверждает себя ясно — уступает, колеблется, ищет внешнего подтверждения.",
                      "There is a deep need for harmony and fairness, but the self may become too dependent on others' approval.",
                      "Глубокая потребность в гармонии и справедливости, но «я» может слишком зависеть от одобрения других.",
                      "Learn to hold your own perspective clearly within relationship — balance means two complete selves, not one merged into the other.",
                      "Научиться ясно удерживать собственную точку зрения в отношениях — баланс означает двух полных людей, а не слияние одного с другим."),
("Sun","Vrishchika"):("Sun in Vrishchika: the soul-principle is drawn to depth, power, and transformation.",
                      "Сурья в Вришчика: принцип души притягивается к глубине, власти и трансформации.",
                      "Identity is forged through crisis and regeneration. The will is intense and magnetic but can become controlling.",
                      "Идентичность закаляется в кризисе и возрождении. Воля интенсивна и магнетична, но может стать контролирующей.",
                      "Turn the drive for power toward inner transformation rather than outer domination — depth is the soul's true territory.",
                      "Направить стремление к власти во внутреннюю трансформацию, а не во внешнее доминирование — глубина является истинной территорией души."),
("Sun","Dhanu"):     ("Sun in Dhanu: the soul-principle expands through wisdom, philosophy, and the search for higher meaning.",
                      "Сурья в Дхану: принцип души расширяется через мудрость, философию и поиск высшего смысла.",
                      "Identity is built around a guiding belief or vision. There is a natural love of teaching and truth-seeking.",
                      "Идентичность строится вокруг направляющей веры или видения. Природная любовь к обучению и поиску истины.",
                      "Keep the vision grounded — the soul serves best when wisdom is lived, not only proclaimed.",
                      "Удерживать видение заземлённым — душа служит лучше всего, когда мудрость прожита, а не только провозглашена."),
("Sun","Makara"):    ("Sun in Makara: the soul-principle achieves through discipline, ambition, and worldly effort.",
                      "Сурья в Макара: принцип души достигает через дисциплину, амбиции и мирские усилия.",
                      "Identity is linked to achievement, status, and responsibility. The capacity for sustained effort is strong.",
                      "Идентичность связана с достижениями, статусом и ответственностью. Способность к устойчивым усилиям сильна.",
                      "Remember that worth is not only earned — allow recognition without needing to constantly justify your presence.",
                      "Помнить, что ценность не только зарабатывается — допускать признание без постоянной необходимости оправдывать своё присутствие."),
("Sun","Kumbha"):    ("Sun in Kumbha: the soul-principle finds itself through collective ideals, social vision, and individuation.",
                      "Сурья в Кумбха: принцип души обнаруживает себя через коллективные идеалы, социальное видение и индивидуацию.",
                      "Identity is paradoxically both unique and group-oriented. There may be tension between personal will and collective belonging.",
                      "Идентичность парадоксально одновременно уникальна и ориентирована на группу. Возможно напряжение между личной волей и коллективной принадлежностью.",
                      "Embrace your distinctiveness within community — the visionary soul serves the collective best by remaining authentically individual.",
                      "Принять свою особенность внутри сообщества — душа-провидец лучше всего служит коллективу, оставаясь подлинно индивидуальной."),
("Sun","Meena"):     ("Sun in Meena: the soul-principle dissolves into compassion, imagination, and spiritual longing.",
                      "Сурья в Меена: принцип души растворяется в сострадании, воображении и духовном стремлении.",
                      "Identity is permeable and empathic. The soul yearns for transcendence but may struggle to assert itself in the material world.",
                      "Идентичность проницаема и эмпатична. Душа стремится к трансценденции, но может с трудом утверждать себя в материальном мире.",
                      "Ground the spiritual sensitivity in concrete creative or service-oriented expression — the soul needs form as much as formlessness.",
                      "Заземлить духовную чуткость в конкретном творческом или служебном выражении — душе нужна форма не меньше, чем бесформенность."),
# ── MOON ──────────────────────────────────────────────────────────────────────
("Moon","Mesha"):    ("Moon in Mesha: the mind responds with immediacy and fire — emotions are quick, direct, and action-oriented.",
                      "Чандра в Меша: ум реагирует мгновенно и огненно — эмоции быстрые, прямые и ориентированные на действие.",
                      "Feelings arise swiftly and express openly. There is courage in emotional response but also reactivity and impatience.",
                      "Чувства возникают стремительно и выражаются открыто. Смелость в эмоциональной реакции, но и реактивность с нетерпеливостью.",
                      "Develop the pause between feeling and reaction — emotional courage deepens when it is chosen, not just reflexive.",
                      "Развивать паузу между чувством и реакцией — эмоциональная смелость углубляется, когда она сознательно выбирается, а не просто рефлекторна."),
("Moon","Vrishabha"):("Moon in Vrishabha is exalted: the mind finds its deepest comfort in beauty, stability, and sensory nourishment.",
                      "Чандра в Вришабха (экзальтация): ум находит глубочайший покой в красоте, стабильности и чувственном питании.",
                      "Emotional life is steady, warm, and patient. There is a gift for creating comfort and an instinct for what is truly nourishing.",
                      "Эмоциональная жизнь устойчива, тепла и терпелива. Дар создавать уют и инстинкт к тому, что по-настоящему питает.",
                      "Watch for emotional attachment to security that resists necessary change — groundedness is a strength, not a wall.",
                      "Остерегаться эмоциональной привязанности к безопасности, сопротивляющейся необходимым переменам — заземлённость — сила, а не стена."),
("Moon","Mithuna"):  ("Moon in Mithuna: the mind is curious, verbal, and emotionally versatile — it processes feelings through thought and conversation.",
                      "Чандра в Митхуна: ум любопытен, вербален и эмоционально разносторонен — чувства обрабатываются через мышление и разговор.",
                      "There is a gift for emotional intelligence expressed through language. The mood changes with new information and stimulation.",
                      "Дар к эмоциональному интеллекту, выражаемому через язык. Настроение меняется вместе с новой информацией и стимуляцией.",
                      "Cultivate emotional depth alongside intellectual facility — let feelings settle rather than always being translated into words.",
                      "Развивать эмоциональную глубину наряду с интеллектуальной лёгкостью — позволять чувствам оседать, а не всегда переводить их в слова."),
("Moon","Karka"):    ("Moon in Karka is in its own sign: the mind is deeply intuitive, nurturing, and attuned to emotional undercurrents.",
                      "Чандра в Карка (своя обитель): ум глубоко интуитивен, заботлив и настроен на эмоциональные течения.",
                      "Feeling and instinct are primary. There is a strong protective instinct and deep sensitivity to the moods of others.",
                      "Чувство и инстинкт первичны. Сильный защитный инстинкт и глубокая чуткость к настроениям других.",
                      "Distinguish between care for others and loss of self — the nurturer also needs nourishment.",
                      "Различать заботу о других и потерю себя — тот, кто питает других, также нуждается в питании."),
("Moon","Simha"):    ("Moon in Simha: the mind seeks emotional expression through creativity, warmth, drama, and the need to be seen.",
                      "Чандра в Симха: ум ищет эмоциональное выражение через творчество, тепло, драму и потребность быть замеченным.",
                      "Feelings are generous, theatrical, and proud. Emotional security is linked to recognition and being valued.",
                      "Чувства щедрые, театральные и гордые. Эмоциональная безопасность связана с признанием и ощущением собственной ценности.",
                      "Let the emotional generosity be unconditional — care that requires applause can exhaust both giver and receiver.",
                      "Позволить эмоциональной щедрости быть безусловной — забота, требующая аплодисментов, истощает и дающего, и получающего."),
("Moon","Kanya"):    ("Moon in Kanya: the mind processes feelings analytically — emotions are refined, observed, and often held to high standards.",
                      "Чандра в Канья: ум перерабатывает чувства аналитически — эмоции утончённые, наблюдаемые, нередко предъявляемые к высоким стандартам.",
                      "There is a gift for emotional discernment but a risk of self-criticism and over-analysis of feelings.",
                      "Дар к эмоциональному различению, но риск самокритики и чрезмерного анализа чувств.",
                      "Trust feeling as information, not as problem to be solved — the heart has its own intelligence that precedes analysis.",
                      "Доверять чувству как информации, а не как проблеме для решения — у сердца есть своя мудрость, предшествующая анализу."),
("Moon","Tula"):     ("Moon in Tula: the mind seeks emotional balance, harmony in relationships, and beauty in its environment.",
                      "Чандра в Тула: ум ищет эмоциональное равновесие, гармонию в отношениях и красоту в окружении.",
                      "Feelings are refined and relational. Emotional security depends heavily on harmonious connections.",
                      "Чувства утончённые и реляционные. Эмоциональная безопасность сильно зависит от гармоничных связей.",
                      "Learn to tolerate emotional discomfort without smoothing it over — sometimes harmony requires honest friction first.",
                      "Научиться переносить эмоциональный дискомфорт, не заглаживая его — иногда гармония требует сначала честного трения."),
("Moon","Vrishchika"):("Moon in Vrishchika is debilitated: the mind plunges into emotional depth, intensity, and the hidden currents beneath surfaces.",
                      "Чандра в Вришчика (падение): ум погружается в эмоциональную глубину, интенсивность и скрытые течения под поверхностью.",
                      "Feelings are transformative and all-or-nothing. There is tremendous depth but also vulnerability to obsession and emotional storms.",
                      "Чувства трансформирующие и по принципу «всё или ничего». Огромная глубина, но также уязвимость к одержимости и эмоциональным бурям.",
                      "Learn to observe the depth without being swept away — emotional mastery comes from feeling fully without losing the witness.",
                      "Научиться наблюдать глубину, не будучи захлёстнутым ею — эмоциональное мастерство приходит от полноты чувствования без потери наблюдателя."),
("Moon","Dhanu"):    ("Moon in Dhanu: the mind seeks emotional nourishment through meaning, adventure, and philosophical exploration.",
                      "Чандра в Дхану: ум ищет эмоциональное питание через смысл, приключения и философское исследование.",
                      "Feelings are expansive and optimistic. Emotional security is found in freedom, belief, and open horizons.",
                      "Чувства широкие и оптимистичные. Эмоциональная безопасность находится в свободе, вере и открытых горизонтах.",
                      "Cultivate emotional presence alongside philosophical vision — the truth you seek is also found in the small, intimate moment.",
                      "Культивировать эмоциональное присутствие наряду с философским видением — искомая истина обнаруживается и в малом, интимном моменте."),
("Moon","Makara"):   ("Moon in Makara: the mind is restrained, responsible, and emotionally disciplined — feelings are managed rather than freely expressed.",
                      "Чандра в Макара: ум сдержан, ответственен и эмоционально дисциплинирован — чувства управляются, а не выражаются свободно.",
                      "There is great emotional endurance and a capacity to carry difficulty with dignity. Emotional needs may be suppressed.",
                      "Огромная эмоциональная выносливость и способность нести трудности с достоинством. Эмоциональные потребности могут подавляться.",
                      "Allow vulnerability as a form of strength — receiving care is as important as providing it.",
                      "Допускать уязвимость как форму силы — получать заботу так же важно, как и давать её."),
("Moon","Kumbha"):   ("Moon in Kumbha: the mind is emotionally idealistic, group-conscious, and somewhat detached from personal feeling.",
                      "Чандра в Кумбха: ум эмоционально идеалистичен, ориентирован на группу и несколько отстранён от личного чувства.",
                      "Emotional life is oriented toward collective causes, friendship, and the universal. Personal intimacy may feel constricting.",
                      "Эмоциональная жизнь ориентирована на коллективные дела, дружбу и универсальное. Личная близость может ощущаться ограничивающей.",
                      "Bridge the universal and the personal — the heart grows when it can be moved by both humanity and by a single person.",
                      "Соединять универсальное и личное — сердце растёт, когда способно быть тронутым как человечеством, так и одним человеком."),
("Moon","Meena"):    ("Moon in Meena: the mind is deeply empathic, imaginative, and permeable to the emotional atmosphere around it.",
                      "Чандра в Меена: ум глубоко эмпатичен, воображаемый и проницаем для эмоциональной атмосферы вокруг него.",
                      "There is a mystical emotional sensitivity and a capacity for profound compassion. Boundaries between self and other are fluid.",
                      "Мистическая эмоциональная чуткость и способность к глубокому состраданию. Границы между собой и другими подвижны.",
                      "Develop discernment about which feelings are yours — protect the inner world without closing it off from the world's depth.",
                      "Развить различение относительно того, какие чувства ваши — защищать внутренний мир, не закрывая его от глубины мира."),
# ── MARS ──────────────────────────────────────────────────────────────────────
("Mars","Mesha"):    ("Mars in Mesha is in its own sign: energy is at its most direct, potent, and self-initiating.",
                      "Мангал в Меша (своя обитель): энергия наиболее прямая, мощная и самостоятельно инициируемая.",
                      "Action is swift and decisive. There is great courage but also impulsiveness — the warrior within acts before reflecting.",
                      "Действие стремительно и решительно. Большая смелость, но и импульсивность — внутренний воин действует раньше, чем думает.",
                      "Harness the power of initiation with strategic patience — courage that waits for the right moment is doubly effective.",
                      "Направить силу инициации со стратегическим терпением — смелость, ждущая правильного момента, вдвойне эффективна."),
("Mars","Vrishabha"):("Mars in Vrishabha: energy is slowed and steadied by earth — effort is patient, material, and enduring.",
                      "Мангал в Вришабха: энергия замедляется и выравнивается землёй — усилие терпеливо, материально и стойко.",
                      "There is great staying power and a drive to build tangible results. Mars here can be stubborn and resistant to change.",
                      "Огромная настойчивость и стремление строить ощутимые результаты. Мангал здесь может быть упрямым и устойчивым к переменам.",
                      "Use persistence as a building force, not an obstacle to renewal — sometimes the most productive action is to release and redirect.",
                      "Использовать настойчивость как строящую силу, а не препятствие обновлению — иногда самое продуктивное действие — отпустить и перенаправить."),
("Mars","Mithuna"):  ("Mars in Mithuna: energy expresses through words, debate, mental agility, and intellectual contest.",
                      "Мангал в Митхуна: энергия выражается через слова, споры, умственную ловкость и интеллектуальное состязание.",
                      "Action is mentally directed. There is a gift for persuasion and strategy, but energy can scatter across too many directions.",
                      "Действие умственно направлено. Дар к убеждению и стратегии, но энергия может рассеиваться по слишком многим направлениям.",
                      "Focus the quick mind on one worthy contest at a time — the sharpest blade is the one that has been aimed.",
                      "Сосредоточить быстрый ум на одном достойном состязании за раз — самый острый клинок тот, что был нацелен."),
("Mars","Karka"):    ("Mars in Karka is debilitated: energy turns inward, becomes defensive, and is filtered through emotional sensitivity.",
                      "Мангал в Карка (падение): энергия обращается вовнутрь, становится защитной и фильтруется через эмоциональную чуткость.",
                      "Action is colored by feeling and instinct. Anger may be expressed indirectly or turned into self-protection.",
                      "Действие окрашено чувством и инстинктом. Гнев может выражаться косвенно или превращаться в самозащиту.",
                      "Learn to express Mars energy directly and without guilt — emotional assertiveness is not the same as aggression.",
                      "Научиться выражать энергию Мангала прямо и без вины — эмоциональная напористость не равна агрессии."),
("Mars","Simha"):    ("Mars in Simha: energy expresses with drama, pride, and the desire to lead, perform, or conquer.",
                      "Мангал в Симха: энергия выражается с драматизмом, гордостью и стремлением вести, выступать или завоёвывать.",
                      "Action is bold and theatrical. There is a strong will to be first and to be admired for it.",
                      "Действие смелое и театральное. Сильное стремление быть первым и получать за это восхищение.",
                      "Direct the solar Mars drive toward genuine contribution — lasting recognition comes from what you build, not only from what you claim.",
                      "Направить солнечный Мангал на подлинный вклад — длительное признание приходит от того, что строишь, а не только от того, что провозглашаешь."),
("Mars","Kanya"):    ("Mars in Kanya: energy is precise, critical, and oriented toward improvement of craft or service.",
                      "Мангал в Канья: энергия точная, критическая и ориентированная на улучшение мастерства или служения.",
                      "Action is methodical and detail-focused. There is a risk of perfectionism blocking decisive movement.",
                      "Действие методично и сосредоточено на деталях. Риск перфекционизма, блокирующего решительное движение.",
                      "Take imperfect action over perfect inaction — the craftsman improves by doing, not by endlessly planning.",
                      "Предпринимать несовершенное действие вместо совершенного бездействия — мастер совершенствуется через делание, а не бесконечное планирование."),
("Mars","Tula"):     ("Mars in Tula: energy is channeled into relationships, justice, and aesthetic or diplomatic action.",
                      "Мангал в Тула: энергия направляется в отношения, справедливость и эстетическое или дипломатическое действие.",
                      "Action is mediated through consideration of others. There may be difficulty acting from pure personal desire without justification.",
                      "Действие опосредовано рассмотрением других. Возможны трудности с действием из чистого личного желания без обоснования.",
                      "Act from your own center within relationship — the warrior does not need permission to stand for what is just.",
                      "Действовать из собственного центра внутри отношений — воин не нуждается в разрешении, чтобы отстаивать справедливость."),
("Mars","Vrishchika"):("Mars in Vrishchika is in its own sign: energy turns toward depth, transformation, hidden power, and the will to master what is dark or difficult.",
                      "Мангал в Вришчика (своя обитель): энергия обращается к глубине, трансформации, скрытой власти и воле к освоению тёмного или трудного.",
                      "The drive is intense, investigative, and magnetic. Power can be used for regeneration or, at its shadow, for control.",
                      "Стремление интенсивное, исследовательское и магнетическое. Власть может использоваться для возрождения или, в тени, для контроля.",
                      "Transform the drive for domination into a drive for mastery of the self — the deepest power is the power over one's own unconscious.",
                      "Трансформировать стремление к доминированию в стремление к мастерству над собой — глубочайшая власть — это власть над собственным бессознательным."),
("Mars","Dhanu"):    ("Mars in Dhanu: energy drives toward vision, adventure, teaching, and the conquest of higher understanding.",
                      "Мангал в Дхану: энергия движется к видению, приключениям, обучению и завоеванию высшего понимания.",
                      "There is enthusiasm for the quest and a fiery idealism. Action can be scattered by too many worthy causes at once.",
                      "Энтузиазм к поиску и огненный идеализм. Действие может рассеиваться из-за слишком многих достойных дел одновременно.",
                      "Commit to one philosophical or practical crusade at a time — the arrow reaches its mark when it is aimed, not scattered.",
                      "Посвятить себя одному философскому или практическому крестовому походу за раз — стрела достигает цели, когда прицелена, а не рассеяна."),
("Mars","Makara"):   ("Mars in Makara is exalted: energy achieves its highest expression through disciplined, strategic, and sustained effort.",
                      "Мангал в Макара (экзальтация): энергия достигает наивысшего выражения через дисциплинированное, стратегическое и устойчивое усилие.",
                      "Action is purposeful and enduring. The will to achieve is remarkable, and practical results are built over time with method.",
                      "Действие целеустремлённо и стойко. Воля к достижению замечательна, а практические результаты выстраиваются со временем методично.",
                      "Ensure that ambition serves values, not only status — the highest achievement is one that also uplifts others.",
                      "Убедиться, что амбиция служит ценностям, а не только статусу — высшее достижение то, которое также поднимает других."),
("Mars","Kumbha"):   ("Mars in Kumbha: energy serves collective ideals, reform, and humanitarian causes rather than personal gain.",
                      "Мангал в Кумбха: энергия служит коллективным идеалам, реформам и гуманитарным делам, а не личной выгоде.",
                      "Action is group-directed and iconoclastic. There is a drive to challenge structures and create change.",
                      "Действие направлено на группу и иконоборческое. Стремление бросать вызов структурам и создавать перемены.",
                      "Ground the reform impulse in practical strategy — the most effective revolutionaries know which battles can actually be won.",
                      "Заземлить реформаторский импульс в практической стратегии — самые эффективные революционеры знают, какие битвы действительно можно выиграть."),
("Mars","Meena"):    ("Mars in Meena: energy dissolves into compassion, imagination, and spiritual or artistic action.",
                      "Мангал в Меена: энергия растворяется в сострадании, воображении и духовном или художественном действии.",
                      "Action is fluid and inspired but can lack direction or assertiveness. The will is gentle and dream-oriented.",
                      "Действие текуче и вдохновенно, но может не иметь направления или напористости. Воля мягкая и ориентированная на мечту.",
                      "Give the inner vision a concrete container — inspired action becomes real when it is given form, timing, and commitment.",
                      "Дать внутреннему видению конкретный сосуд — вдохновенное действие становится реальным, когда ему придаётся форма, время и обязательство."),
# ── MERCURY ───────────────────────────────────────────────────────────────────
("Mercury","Mesha"):("Mercury in Mesha: the mind is quick, direct, bold, and initiating in its communication.",
                     "Будха в Меша: ум быстрый, прямой, смелый и инициирующий в коммуникации.",
                     "Thinking is spontaneous and decisive. Words come before reflection; ideas arrive as impulses.",
                     "Мышление спонтанно и решительно. Слова приходят раньше рефлексии; идеи приходят как импульсы.",
                     "Cultivate the discipline of listening as an equal partner to speaking — the sharpest mind also knows when to receive.",
                     "Развивать дисциплину слушания как равного партнёра говорению — острейший ум также знает, когда получать."),
("Mercury","Vrishabha"):("Mercury in Vrishabha: the mind is deliberate, practical, and drawn to beauty and material understanding.",
                         "Будха в Вришабха: ум обдуманный, практичный и притягивается к красоте и материальному пониманию.",
                         "Thinking moves slowly but arrives at lasting conclusions. There is a gift for working with form, texture, and value.",
                         "Мышление движется медленно, но приходит к прочным выводам. Дар работы с формой, текстурой и ценностью.",
                         "Trust the slow mind's depth — not every answer needs to arrive instantly to be correct.",
                         "Доверять глубине медленного ума — не каждый ответ должен приходить мгновенно, чтобы быть правильным."),
("Mercury","Mithuna"):("Mercury in Mithuna is in its own sign: intellect is at its most versatile, nimble, and communicatively gifted.",
                       "Будха в Митхуна (своя обитель): интеллект наиболее разносторонний, гибкий и одарённый в коммуникации.",
                       "The mind leaps between ideas with ease. There is a love of language, learning, and the pleasure of exchange.",
                       "Ум легко перепрыгивает между идеями. Любовь к языку, учению и удовольствию обмена.",
                       "Deepen one body of knowledge rather than perpetually sampling — brilliance matures into mastery through sustained focus.",
                       "Углублять одну область знаний, а не постоянно пробовать разное — блеск созревает в мастерство через устойчивый фокус."),
("Mercury","Karka"):("Mercury in Karka: the mind is intuitive, emotionally colored, and strongly influenced by memory and feeling.",
                     "Будха в Карка: ум интуитивен, эмоционально окрашен и сильно влияет на него память и чувство.",
                     "Thinking is associative and image-rich. Facts are understood through personal experience and emotional resonance.",
                     "Мышление ассоциативно и богато образами. Факты понимаются через личный опыт и эмоциональный резонанс.",
                     "Develop discernment between intuition and projection — not all emotionally compelling thoughts are accurate reflections of reality.",
                     "Развить различение между интуицией и проекцией — не все эмоционально убедительные мысли являются точным отражением реальности."),
("Mercury","Simha"):("Mercury in Simha: the mind is proud, creative, and communicates with dramatic flair and authority.",
                     "Будха в Симха: ум гордый, творческий, общается с драматизмом и авторитетом.",
                     "There is a gift for storytelling and commanding speech. The mind can struggle to hear perspectives that challenge its certainties.",
                     "Дар к рассказыванию историй и командной речи. Ум может испытывать трудности с восприятием точек зрения, оспаривающих его уверенность.",
                     "Let curiosity temper authority — the most compelling communicator is also genuinely interested in what others think.",
                     "Позволить любопытству умерять авторитет — самый убедительный коммуникатор также искренне интересуется тем, что думают другие."),
("Mercury","Kanya"):("Mercury in Kanya is exalted and in its own sign: intellect reaches its highest precision, discernment, and analytical depth.",
                     "Будха в Канья (экзальтация, своя обитель): интеллект достигает наивысшей точности, различения и аналитической глубины.",
                     "The mind is systematic, exact, and skilled at improvement. Perfectionistic tendencies can create excessive self-criticism.",
                     "Ум систематический, точный и умелый в улучшении. Перфекционистские тенденции могут создавать чрезмерную самокритику.",
                     "Use the analytical gift to build rather than to limit — precise thought serves creation when it becomes a tool, not a judge.",
                     "Использовать аналитический дар для созидания, а не для ограничения — точная мысль служит созданию, когда становится инструментом, а не судьёй."),
("Mercury","Tula"):("Mercury in Tula: the mind seeks balanced judgment, diplomatic framing, and intellectual harmony.",
                    "Будха в Тула: ум ищет сбалансированного суждения, дипломатической формулировки и интеллектуальной гармонии.",
                    "Thinking naturally considers multiple perspectives. Decisions may be delayed by the desire to be perfectly fair.",
                    "Мышление естественно рассматривает множество точек зрения. Решения могут откладываться из-за желания быть абсолютно справедливым.",
                    "Make the decision even when perfect fairness is impossible — discernment in action is a form of justice.",
                    "Принимать решение, даже когда идеальная справедливость невозможна — различение в действии является формой справедливости."),
("Mercury","Vrishchika"):("Mercury in Vrishchika: the mind penetrates surfaces, investigates hidden patterns, and thinks with intensity and purpose.",
                           "Будха в Вришчика: ум проникает сквозь поверхности, исследует скрытые паттерны и мыслит с интенсивностью и целеустремлённостью.",
                           "Thinking is strategic and psychologically acute. There is a gift for research, investigation, and seeing what others miss.",
                           "Мышление стратегическое и психологически острое. Дар к исследованию, расследованию и видению того, что упускают другие.",
                           "Beware of the tendency to interpret everything through suspicion — depth need not always mean darkness.",
                           "Остерегаться тенденции интерпретировать всё через подозрение — глубина не всегда означает тьму."),
("Mercury","Dhanu"):("Mercury in Dhanu: the mind ranges across broad vistas, philosophical questions, and the big picture.",
                     "Будха в Дхану: ум охватывает широкие горизонты, философские вопросы и общую картину.",
                     "Thinking is enthusiastic and expansive but can overlook detail. There is a love of ideas that encompass and inspire.",
                     "Мышление энтузиастическое и широкое, но может упускать детали. Любовь к идеям, которые охватывают и вдохновляют.",
                     "Anchor grand ideas in practical steps — the visionary mind serves best when it can also count what is needed.",
                     "Заземлить великие идеи в практических шагах — ум-провидец служит лучше всего, когда также способен подсчитать то, что необходимо."),
("Mercury","Makara"):("Mercury in Makara: the mind is structured, pragmatic, and focused on what is useful, measurable, and achievable.",
                      "Будха в Макара: ум структурированный, прагматичный и сосредоточен на том, что полезно, измеримо и достижимо.",
                      "Thinking moves from principle to practical application. There is a gift for long-term planning and systematic strategy.",
                      "Мышление движется от принципа к практическому применению. Дар к долгосрочному планированию и системной стратегии.",
                      "Allow creativity and intuition to inform the practical mind — not all valuable intelligence arrives in orderly form.",
                      "Позволить творчеству и интуиции информировать практический ум — не весь ценный интеллект приходит в упорядоченной форме."),
("Mercury","Kumbha"):("Mercury in Kumbha: the mind is original, innovative, and drawn to ideas that challenge convention.",
                      "Будха в Кумбха: ум оригинальный, инновационный и притягивается к идеям, бросающим вызов условностям.",
                      "Thinking is inventive and group-oriented. There is a love of systems, networks, and ideas that apply to everyone.",
                      "Мышление изобретательное и ориентированное на группу. Любовь к системам, сетям и идеям, применимым ко всем.",
                      "Ground the inventive mind in lived experience — revolutionary ideas gain force when they are tested, not only theorized.",
                      "Заземлить изобретательный ум в прожитом опыте — революционные идеи обретают силу, когда проверяются, а не только теоретизируются."),
("Mercury","Meena"):("Mercury in Meena is debilitated: the rational mind is softened by imagination, intuition, and spiritual longing.",
                     "Будха в Меена (падение): рациональный ум смягчается воображением, интуицией и духовным стремлением.",
                     "Thinking is poetic, empathic, and imaginative. Logic may dissolve into feeling; boundaries between fact and fantasy can blur.",
                     "Мышление поэтическое, эмпатическое и образное. Логика может растворяться в чувстве; границы между фактом и фантазией могут размываться.",
                     "Develop practical grounding alongside creative vision — the inspired mind needs form and method to bring its gifts into the world.",
                     "Развить практическую заземлённость наряду с творческим видением — вдохновенный ум нуждается в форме и методе, чтобы принести свои дары в мир."),
# ── JUPITER ───────────────────────────────────────────────────────────────────
("Jupiter","Mesha"):("Jupiter in Mesha: wisdom expresses through initiative, boldness, and the pioneering pursuit of higher ideals.",
                     "Гуру в Меша: мудрость выражается через инициативу, смелость и первопроходческое стремление к высшим идеалам.",
                     "Growth comes through courageous action. There is enthusiasm for the new, and teaching flows through direct example.",
                     "Рост приходит через смелое действие. Энтузиазм к новому, и обучение течёт через прямой пример.",
                     "Pair the initiating vision with the patience to see it through — wisdom is not only in the spark but in sustaining the flame.",
                     "Сочетать инициирующее видение с терпением его воплощения — мудрость не только в искре, но и в поддержании пламени."),
("Jupiter","Vrishabha"):("Jupiter in Vrishabha: wisdom is found through beauty, material abundance, and the patient cultivation of value.",
                          "Гуру в Вришабха: мудрость обнаруживается через красоту, материальное изобилие и терпеливое взращивание ценности.",
                          "Growth is steady and tangible. Grace flows through sensory experience, art, and the generosity of sustaining others.",
                          "Рост стабильный и ощутимый. Благодать течёт через чувственный опыт, искусство и щедрость поддержки других.",
                          "Be generous without over-accumulating — Jupiter in earth flourishes when abundance is shared.",
                          "Быть щедрым, не накапливая чрезмерно — Гуру в земле процветает, когда изобилием делятся."),
("Jupiter","Mithuna"):("Jupiter in Mithuna: wisdom multiplies through learning, dialogue, and the exploration of many ideas and perspectives.",
                       "Гуру в Митхуна: мудрость умножается через обучение, диалог и исследование многих идей и перспектив.",
                       "Growth comes through intellectual breadth and the ability to synthesize diverse knowledge.",
                       "Рост приходит через интеллектуальную широту и способность синтезировать разнообразные знания.",
                       "Move from information to wisdom — gathering knowledge is only the first step; integration is where Jupiter's grace truly activates.",
                       "Двигаться от информации к мудрости — сбор знаний лишь первый шаг; интеграция — вот где по-настоящему активируется благодать Гуру."),
("Jupiter","Karka"):("Jupiter in Karka is exalted: wisdom flows through emotional intelligence, care, and the nurturing of what is most sacred.",
                     "Гуру в Карка (экзальтация): мудрость течёт через эмоциональный интеллект, заботу и взращивание наиболее священного.",
                     "Grace is most naturally expressed through compassion, family, and the protection of the vulnerable.",
                     "Благодать наиболее естественно выражается через сострадание, семью и защиту уязвимых.",
                     "Let emotional wisdom guide without smothering — the highest form of care also allows freedom.",
                     "Позволить эмоциональной мудрости направлять, не удушая — высшая форма заботы также допускает свободу."),
("Jupiter","Simha"):("Jupiter in Simha: wisdom radiates through creative power, generous leadership, and the celebration of life's greatness.",
                     "Гуру в Симха: мудрость излучается через творческую силу, щедрое лидерство и прославление величия жизни.",
                     "Growth comes through authentic self-expression. There is a natural teacher who inspires through example and warmth.",
                     "Рост приходит через подлинное самовыражение. Природный учитель, вдохновляющий через пример и тепло.",
                     "Balance the desire for recognition with genuine service — the greatest leaders teach by being fully themselves.",
                     "Уравновешивать желание признания с подлинным служением — величайшие лидеры учат, будучи полностью собой."),
("Jupiter","Kanya"):("Jupiter in Kanya: wisdom is expressed through discernment, service, and the improvement of practical conditions.",
                     "Гуру в Канья: мудрость выражается через различение, служение и улучшение практических условий.",
                     "Growth comes through refinement and helpful contribution. The teacher here is careful, detailed, and oriented toward healing.",
                     "Рост приходит через совершенствование и полезный вклад. Учитель здесь внимателен, детален и ориентирован на исцеление.",
                     "Expand beyond perfectionism — wisdom grows when it accepts that imperfect service is still invaluable.",
                     "Расширяться за пределы перфекционизма — мудрость растёт, когда принимает, что несовершенное служение всё равно бесценно."),
("Jupiter","Tula"):("Jupiter in Tula: wisdom is found through relationship, beauty, justice, and the art of harmonious coexistence.",
                    "Гуру в Тула: мудрость обнаруживается через отношения, красоту, справедливость и искусство гармоничного сосуществования.",
                    "Growth comes through genuine partnership and the careful weighing of different perspectives.",
                    "Рост приходит через подлинное партнёрство и тщательное взвешивание различных точек зрения.",
                    "Ground idealism in concrete relational practice — justice requires not only the vision but the difficult daily work of fairness.",
                    "Заземлить идеализм в конкретной реляционной практике — справедливость требует не только видения, но и трудной ежедневной работы по справедливости."),
("Jupiter","Vrishchika"):("Jupiter in Vrishchika: wisdom is found through transformation, depth psychology, and the courage to face what is hidden.",
                           "Гуру в Вришчика: мудрость обнаруживается через трансформацию, глубинную психологию и смелость встретить скрытое.",
                           "Growth comes through crisis, regeneration, and the investigation of life's most profound mysteries.",
                           "Рост приходит через кризис, возрождение и исследование самых глубоких тайн жизни.",
                           "Use the knowledge of shadow for healing rather than for power — the deepest wisdom transforms rather than controls.",
                           "Использовать знание тени для исцеления, а не для власти — глубочайшая мудрость трансформирует, а не контролирует."),
("Jupiter","Dhanu"):("Jupiter in Dhanu is in its own sign: wisdom is at its most expansive, generous, and philosophically alive.",
                     "Гуру в Дхану (своя обитель): мудрость наиболее широкая, щедрая и философски живая.",
                     "Growth comes easily through learning, travel, teaching, and the pursuit of meaning. There is abundant faith in life's goodness.",
                     "Рост приходит легко через обучение, путешествия, преподавание и поиск смысла. Обильная вера в доброту жизни.",
                     "Balance optimism with discernment — not every path leads to truth, and the teacher who questions their own assumptions grows most.",
                     "Уравновешивать оптимизм с различением — не каждый путь ведёт к истине, и учитель, ставящий под сомнение собственные допущения, растёт больше всего."),
("Jupiter","Makara"):("Jupiter in Makara is debilitated: wisdom contracts into practical ambition and can mistake worldly achievement for true growth.",
                      "Гуру в Макара (падение): мудрость сжимается в практические амбиции и может путать мирские достижения с истинным ростом.",
                      "Jupiter is disciplined but can lose its expansive, generous quality. Growth is slow and materially oriented.",
                      "Гуру дисциплинирован, но может потерять расширяющееся, щедрое качество. Рост медленный и материально ориентированный.",
                      "Recover the gift of inner expansion alongside outer achievement — wisdom that cannot transcend its own structure eventually limits itself.",
                      "Восстановить дар внутреннего расширения наряду с внешним достижением — мудрость, не способная выйти за пределы собственной структуры, в конечном счёте ограничивает себя."),
("Jupiter","Kumbha"):("Jupiter in Kumbha: wisdom expands into universal concern, social vision, and the understanding of humanity's collective potential.",
                      "Гуру в Кумбха: мудрость расширяется до универсальной заботы, социального видения и понимания коллективного потенциала человечества.",
                      "Growth comes through community, progressive ideals, and the willingness to serve something larger than personal gain.",
                      "Рост приходит через сообщество, прогрессивные идеалы и готовность служить чему-то большему, чем личная выгода.",
                      "Root the vision in human connection — the most expansive ideas are those that can also be felt.",
                      "Укоренить видение в человеческой связи — наиболее широкие идеи те, которые также можно ощутить."),
("Jupiter","Meena"):("Jupiter in Meena is in its own sign: wisdom dissolves into compassion, spiritual depth, and the unity of all existence.",
                     "Гуру в Меена (своя обитель): мудрость растворяется в сострадании, духовной глубине и единстве всего сущего.",
                     "Growth comes through surrender, meditation, and service to those most in need. There is a gift for spiritual teaching.",
                     "Рост приходит через самоотдачу, медитацию и служение тем, кто больше всего нуждается. Дар к духовному учению.",
                     "Ground compassion in discernment — the teacher who can distinguish healthy surrender from unhealthy self-loss serves most wisely.",
                     "Заземлить сострадание в различении — учитель, способный различить здоровую самоотдачу от нездоровой потери себя, служит наиболее мудро."),
# ── VENUS ─────────────────────────────────────────────────────────────────────
("Venus","Mesha"):  ("Venus in Mesha: love and beauty express through boldness, passion, and the desire for direct and immediate connection.",
                     "Шукра в Меша: любовь и красота выражаются через смелость, страсть и стремление к прямой и непосредственной связи.",
                     "Attraction is intense and immediate. Relationships are pursued with initiative but may lack patience for long development.",
                     "Притяжение интенсивное и немедленное. Отношения завязываются с инициативой, но могут не хватать терпения для долгого развития.",
                     "Cultivate patience and depth in love — the most passionate bond is the one that is also tended over time.",
                     "Развивать терпение и глубину в любви — самая страстная связь та, что также заботливо взращивается со временем."),
("Venus","Vrishabha"):("Venus in Vrishabha is in its own sign: beauty and love express most naturally through sensory delight, loyalty, and enduring value.",
                       "Шукра в Вришабха (своя обитель): красота и любовь выражаются наиболее естественно через чувственное наслаждение, верность и прочную ценность.",
                       "Pleasure is a natural gift. Relationships are built on comfort, stability, and genuine physical warmth.",
                       "Удовольствие — природный дар. Отношения строятся на комфорте, стабильности и подлинном физическом тепле.",
                       "Balance enjoyment with openness to change — beauty also lives in the unexpected, not only in what is safe and familiar.",
                       "Уравновешивать наслаждение с открытостью к переменам — красота также живёт в неожиданном, не только в безопасном и привычном."),
("Venus","Mithuna"): ("Venus in Mithuna: love and beauty find expression through wit, intellectual connection, and the pleasure of shared ideas.",
                      "Шукра в Митхуна: любовь и красота находят выражение через остроумие, интеллектуальную связь и удовольствие от общих идей.",
                      "Relationships thrive on mental stimulation and playful exchange. The heart wants variety as much as constancy.",
                      "Отношения процветают на умственной стимуляции и игривом обмене. Сердце хочет разнообразия не меньше, чем постоянства.",
                      "Develop emotional depth alongside intellectual pleasure — love grows deepest when the conversation also includes silence.",
                      "Развивать эмоциональную глубину наряду с интеллектуальным удовольствием — любовь растёт глубже всего, когда разговор также включает молчание."),
("Venus","Karka"):  ("Venus in Karka: love is nurturing, deeply feeling, and oriented toward home, family, and emotional safety.",
                     "Шукра в Карка: любовь питающая, глубоко чувствующая и ориентированная на дом, семью и эмоциональную безопасность.",
                     "Beauty is found in intimacy and belonging. Relationships are cherished and protected, sometimes to the point of possessiveness.",
                     "Красота обнаруживается в близости и принадлежности. Отношения лелеются и защищаются, иногда до степени собственничества.",
                     "Allow love to be expansive rather than only protective — true belonging includes the freedom to be fully oneself.",
                     "Позволить любви быть широкой, а не только защитной — подлинная принадлежность включает свободу быть полностью собой."),
("Venus","Simha"):  ("Venus in Simha: love is generous, dramatic, and drawn to grandeur, celebration, and the radiance of creative life.",
                     "Шукра в Симха: любовь щедрая, драматичная и притягивается к величию, торжеству и сиянию творческой жизни.",
                     "There is warmth and theatrical beauty in how love is expressed. Recognition and admiration are central to relational fulfillment.",
                     "Тепло и театральная красота в том, как выражается любовь. Признание и восхищение занимают центральное место в реляционном удовлетворении.",
                     "Let love be unconditional as well as generous — the heart that can give without expecting applause grows most radiant.",
                     "Позволить любви быть безусловной, а также щедрой — сердце, способное давать без ожидания аплодисментов, сияет ярче всего."),
("Venus","Kanya"):  ("Venus in Kanya is debilitated: love is expressed through careful service, refinement, and practical dedication — but may struggle with full openness.",
                     "Шукра в Канья (падение): любовь выражается через тщательное служение, утончённость и практическую преданность — но может испытывать трудности с полной открытостью.",
                     "Affection is shown through acts of help and attention to detail. There may be difficulty with spontaneous intimacy.",
                     "Привязанность выражается через поступки помощи и внимание к деталям. Возможны трудности со спонтанной близостью.",
                     "Practice vulnerability as an act of courage — love that can only be offered through service never fully lands.",
                     "Практиковать уязвимость как акт смелости — любовь, которую можно предложить только через служение, никогда не достигает полностью."),
("Venus","Tula"):   ("Venus in Tula is in its own sign: love and beauty are at their most balanced, harmonious, and relationally refined.",
                     "Шукра в Тула (своя обитель): любовь и красота наиболее сбалансированные, гармоничные и реляционно утончённые.",
                     "There is a natural gift for relationship, aesthetics, and the art of meeting others with grace.",
                     "Природный дар к отношениям, эстетике и искусству встречи других с изяществом.",
                     "Develop the capacity to hold your own needs clearly within partnership — harmony that requires self-erasure is not true balance.",
                     "Развить способность ясно удерживать собственные потребности внутри партнёрства — гармония, требующая самостирания, не является истинным балансом."),
("Venus","Vrishchika"):("Venus in Vrishchika: love is intense, magnetic, and transformative — the heart seeks depth and profound union rather than surface beauty.",
                        "Шукра в Вришчика: любовь интенсивная, магнетическая и трансформирующая — сердце ищет глубины и глубокого единения, а не поверхностной красоты.",
                        "Attraction is all-or-nothing and profoundly bonding. There is a need to merge completely and a risk of possessiveness.",
                        "Притяжение по принципу «всё или ничего» и глубоко связывающее. Потребность полностью слиться и риск собственничества.",
                        "Let love also breathe — depth and union grow most authentically when each person retains their individual wholeness.",
                        "Позволить любви также дышать — глубина и единство растут наиболее подлинно, когда каждый человек сохраняет свою индивидуальную целостность."),
("Venus","Dhanu"):  ("Venus in Dhanu: love is adventurous, philosophical, and oriented toward freedom and the expansion of mutual horizons.",
                     "Шукра в Дхану: любовь приключенческая, философская и ориентированная на свободу и расширение взаимных горизонтов.",
                     "Beauty is found in shared exploration and the joy of discovery together. Commitment may feel limiting to the free heart.",
                     "Красота обнаруживается в совместном исследовании и радости открытия вместе. Обязательство может ощущаться ограничивающим для свободного сердца.",
                     "Find the adventure within commitment as well as beyond it — the deepest journey often happens within one profound relationship.",
                     "Найти приключение внутри обязательства, а также за его пределами — самое глубокое путешествие нередко происходит внутри одних глубоких отношений."),
("Venus","Makara"): ("Venus in Makara: love is expressed through loyalty, responsibility, and the slow, steady building of lasting bonds.",
                     "Шукра в Макара: любовь выражается через верность, ответственность и медленное, устойчивое построение прочных связей.",
                     "Beauty is found in what endures. Relationships are taken seriously and commitment is honored above impulse.",
                     "Красота обнаруживается в том, что продолжается. Отношения воспринимаются серьёзно, и обязательство ценится выше импульса.",
                     "Allow warmth and spontaneity alongside reliability — love also needs play, tenderness, and the unexpected.",
                     "Допускать тепло и спонтанность наряду с надёжностью — любовь также нуждается в игре, нежности и неожиданном."),
("Venus","Kumbha"): ("Venus in Kumbha: love expresses through friendship, intellectual equality, and the freedom to be authentically individual within relationship.",
                     "Шукра в Кумбха: любовь выражается через дружбу, интеллектуальное равенство и свободу быть подлинно индивидуальным внутри отношений.",
                     "The ideal partnership is one of mutual respect, shared vision, and creative companionship.",
                     "Идеальное партнёрство — это взаимное уважение, общее видение и творческое товарищество.",
                     "Welcome emotional intimacy alongside intellectual connection — the heart needs more than shared ideas; it also needs to be held.",
                     "Принимать эмоциональную близость наряду с интеллектуальной связью — сердцу нужно больше, чем общие идеи; ему также нужно быть принятым."),
("Venus","Meena"):  ("Venus in Meena is exalted: love dissolves boundaries between self and other into compassion, devotion, and transcendent beauty.",
                     "Шукра в Меена (экзальтация): любовь растворяет границы между собой и другим в сострадании, преданности и трансцендентной красоте.",
                     "The heart opens naturally to beauty, art, spirit, and the suffering of others. There is a gift for devotional love.",
                     "Сердце естественно открывается красоте, искусству, духу и страданиям других. Дар к преданностной любви.",
                     "Ground the devotional heart in self-care and discernment — love that dissolves the self entirely serves no one fully.",
                     "Заземлить преданное сердце в самозаботе и различении — любовь, полностью растворяющая «я», не служит никому в полной мере."),
# ── SATURN ────────────────────────────────────────────────────────────────────
("Saturn","Mesha"): ("Saturn in Mesha is debilitated: the principle of discipline and limitation meets the fiery impulse to act — tension arises between restraint and initiative.",
                     "Шани в Меша (падение): принцип дисциплины и ограничения встречает огненный импульс к действию — возникает напряжение между сдержанностью и инициативой.",
                     "Action is inhibited by caution or fear, or swings to reactive impulsiveness. Learning to act despite limitation is the karmic task.",
                     "Действие сдерживается осторожностью или страхом, или качается к реактивной импульсивности. Учиться действовать несмотря на ограничение — кармическая задача.",
                     "Learn to initiate with patience — courage is not the absence of Saturn's caution but the choice to act through it.",
                     "Научиться инициировать с терпением — смелость не является отсутствием осторожности Шани, но выбором действовать несмотря на неё."),
("Saturn","Vrishabha"):("Saturn in Vrishabha: discipline is applied to material life, resources, and the slow building of lasting security.",
                        "Шани в Вришабха: дисциплина применяется к материальной жизни, ресурсам и медленному строительству прочной безопасности.",
                        "There is great patience and endurance in building tangible results. Fear of loss or scarcity may drive over-attachment.",
                        "Огромное терпение и выносливость в строительстве ощутимых результатов. Страх потери или нехватки может вести к чрезмерной привязанности.",
                        "Trust the process of gradual accumulation — Saturn in earth builds what lasts, one consistent layer at a time.",
                        "Доверять процессу постепенного накопления — Шани в земле строит то, что продолжается, один последовательный слой за раз."),
("Saturn","Mithuna"):("Saturn in Mithuna: discipline is applied to thought, communication, and the mastery of language or knowledge.",
                      "Шани в Митхуна: дисциплина применяется к мышлению, коммуникации и мастерству языка или знания.",
                      "The mind works seriously and carefully. Communication may be restrained or experienced as burdensome.",
                      "Ум работает серьёзно и тщательно. Коммуникация может быть сдержанной или ощущаться обременительной.",
                      "Use Saturn's discipline to develop mastery in one form of communication — restrained speech delivered with precision is more powerful than much that is said.",
                      "Использовать дисциплину Шани для развития мастерства в одной форме коммуникации — сдержанная речь, доставленная с точностью, мощнее многого сказанного."),
("Saturn","Karka"):  ("Saturn in Karka: discipline meets emotional life — there is difficulty with nurturing freely or receiving care without guilt.",
                      "Шани в Карка: дисциплина встречает эмоциональную жизнь — трудности с свободным питанием или получением заботы без вины.",
                      "Emotional needs are suppressed or structured. There may be a sense of emotional isolation even within relationships.",
                      "Эмоциональные потребности подавляются или структурируются. Может ощущаться эмоциональная изоляция даже внутри отношений.",
                      "Practice receiving care as a karmic task — Saturn here learns that allowing nourishment is not weakness but earned wisdom.",
                      "Практиковать получение заботы как кармическую задачу — Шани здесь учится, что допускать питание — не слабость, а заработанная мудрость."),
("Saturn","Simha"):  ("Saturn in Simha: discipline is applied to self-expression, creativity, and the desire for recognition.",
                      "Шани в Симха: дисциплина применяется к самовыражению, творчеству и стремлению к признанию.",
                      "The creative drive is serious, structured, and often delayed. There may be fear of performing or being seen.",
                      "Творческое стремление серьёзно, структурировано и нередко отложено. Может быть страх выступления или того, чтобы быть замеченным.",
                      "Commit to the long craft of creative discipline — Saturn's gifts in Leo arrive in maturity as lasting, authoritative creative work.",
                      "Посвятить себя длительному ремеслу творческой дисциплины — дары Шани в Льве приходят в зрелости как прочная, авторитетная творческая работа."),
("Saturn","Kanya"):  ("Saturn in Kanya: discipline is applied to service, health, and the perfection of practical craft.",
                      "Шани в Канья: дисциплина применяется к служению, здоровью и совершенствованию практического ремесла.",
                      "There is a remarkable capacity for sustained, precise work. Perfectionism can become paralyzing rather than productive.",
                      "Замечательная способность к устойчивой, точной работе. Перфекционизм может стать парализующим, а не продуктивным.",
                      "Distinguish between high standards and punishing self-demands — Saturn in Virgo is most productive when it serves health, not fear.",
                      "Различать высокие стандарты и наказывающие требования к себе — Шани в Деве наиболее продуктивен, когда служит здоровью, а не страху."),
("Saturn","Tula"):   ("Saturn in Tula is exalted: the principle of law, fairness, and relational structure is at its most refined and effective.",
                      "Шани в Тула (экзальтация): принцип закона, справедливости и реляционной структуры наиболее утончён и эффективен.",
                      "There is a gift for principled relationship, mediation, and the creation of fair systems.",
                      "Дар к принципиальным отношениям, медиации и созданию справедливых систем.",
                      "Apply Saturn's justice with compassion as well as rigor — the fairest systems are those that also make room for the human.",
                      "Применять справедливость Шани с состраданием, а также строгостью — самые справедливые системы те, что также оставляют место для человеческого."),
("Saturn","Vrishchika"):("Saturn in Vrishchika: discipline is applied to power, transformation, and the mastery of hidden or difficult forces.",
                          "Шани в Вришчика: дисциплина применяется к власти, трансформации и освоению скрытых или трудных сил.",
                          "The karmic task involves confronting the shadow, managing deep drives, and transforming what is feared or suppressed.",
                          "Кармическая задача включает встречу с тенью, управление глубокими стремлениями и трансформацию того, что вызывает страх или подавляется.",
                          "Saturn here teaches that the most enduring power is gained by mastering oneself, not by controlling others.",
                          "Шани здесь учит, что наиболее прочная власть обретается через освоение себя, а не через контроль других."),
("Saturn","Dhanu"):  ("Saturn in Dhanu: discipline is applied to belief, philosophy, and the patient construction of a meaningful worldview.",
                      "Шани в Дхану: дисциплина применяется к вере, философии и терпеливому строительству значимого мировоззрения.",
                      "There is a serious and responsible approach to truth-seeking. Philosophical conviction is earned through years of testing.",
                      "Серьёзный и ответственный подход к поиску истины. Философское убеждение зарабатывается годами испытаний.",
                      "Allow the wisdom to breathe between the disciplines — Saturn in Sagittarius grows through structure and faith working together.",
                      "Позволить мудрости дышать между дисциплинами — Шани в Стрельце растёт через структуру и веру, работающие вместе."),
("Saturn","Makara"): ("Saturn in Makara is in its own sign: discipline, ambition, and worldly achievement are expressed with maximum focus and endurance.",
                      "Шани в Макара (своя обитель): дисциплина, амбиции и мирские достижения выражаются с максимальной сосредоточенностью и стойкостью.",
                      "The will to achieve is extraordinary. Results come slowly but are permanent. There is great responsibility and authority.",
                      "Воля к достижению экстраординарна. Результаты приходят медленно, но являются постоянными. Огромная ответственность и авторитет.",
                      "Ensure that worldly achievement rests on a foundation of inner integrity — what Saturn builds in Capricorn must be worth building.",
                      "Убедиться, что мирские достижения покоятся на основе внутренней целостности — то, что Шани строит в Козероге, должно стоить строительства."),
("Saturn","Kumbha"): ("Saturn in Kumbha is in its own sign: discipline structures social vision, and the individual's karmic task is in service of collective betterment.",
                      "Шани в Кумбха (своя обитель): дисциплина структурирует социальное видение, и кармическая задача индивидуума в служении коллективному улучшению.",
                      "There is a serious commitment to social reform, community structures, and systemic change.",
                      "Серьёзная приверженность социальным реформам, общественным структурам и системным переменам.",
                      "Balance the universal vision with present personal connection — the system is built by people who are also genuinely present to one another.",
                      "Уравновешивать универсальное видение с настоящей личной связью — система строится людьми, которые также подлинно присутствуют друг для друга."),
("Saturn","Meena"):  ("Saturn in Meena: discipline meets spiritual surrender — the karmic task is to build structure that also allows dissolution.",
                      "Шани в Меена: дисциплина встречает духовную самоотдачу — кармическая задача состоит в построении структуры, которая также допускает растворение.",
                      "There is difficulty reconciling responsibility with spiritual longing. Practical duties and inner life may feel at war.",
                      "Трудность примирения ответственности с духовным стремлением. Практические обязанности и внутренняя жизнь могут ощущаться как война.",
                      "Find the sacred in the daily — Saturn in Pisces matures when spiritual practice becomes a reliable, structured part of ordinary life.",
                      "Найти священное в повседневном — Шани в Рыбах созревает, когда духовная практика становится надёжной, структурированной частью обычной жизни."),
}

# ── Build rules ────────────────────────────────────────────────────────────────
ORDINALS = {1:'1st',2:'2nd',3:'3rd',4:'4th',5:'5th',6:'6th',
            7:'7th',8:'8th',9:'9th',10:'10th',11:'11th',12:'12th'}

rules = []
for graha_key, gd in GRAHAS.items():
    for i, rdata in enumerate(RASHIS, 1):
        rashi, rashi_ru, ruler, element, mode, rashi_en, rashi_ru_desc = rdata
        dignity_en, dignity_ru = dignity(graha_key, rashi, gd)

        rid = f'vedic-rule.graha-rashi.{graha_key.lower()}-in-{rashi.lower()}'
        interp = INTERP.get((graha_key, rashi))

        if interp:
            s_en, s_ru, p_en, p_ru, g_en, g_ru = interp
        else:
            s_en = f'{graha_key} in {rashi}: {gd["principle_en"]} meets the field of {rashi_en}.'
            s_ru = f'{gd["ru"]} в {rashi_ru}: {gd["principle_ru"]} встречается с полем {rashi_ru_desc}.'
            p_en = f'The {dignity_en} placement shapes how this combination expresses in the chart.'
            p_ru = f'Положение {dignity_ru} формирует, как эта комбинация выражается в карте.'
            g_en = f'Consciously integrate the principle of {gd["principle_en"]} within the field of {rashi_en}.'
            g_ru = f'Осознанно интегрировать принцип {gd["principle_ru"]} в поле {rashi_ru_desc}.'

        rule = {
            'id': rid,
            'system': 'vedic',
            'methodFamily': 'psychological-vedic',
            'factor': {'graha': graha_key, 'rashi': rashi},
            'dignity': {'status': dignity_en, 'statusRu': dignity_ru},
            'sourceIds': ['source.narasimha-rao-vedic-integrated', 'source.agarwal-vedic-v2'],
            'themes': [graha_key.lower(), rashi.lower(), element, mode, dignity_en.split()[0]],
            'themesRu': [gd['ru'], rashi_ru, element, dignity_ru.split()[0]],
            'simple': {
                'summary': s_en,
                'pattern': p_en,
                'growth': g_en,
                'reflection': f'How does the quality of {rashi_en} shape how you express {gd["principle_en"]}?',
            },
            'simpleRu': {
                'summary': s_ru,
                'pattern': p_ru,
                'growth': g_ru,
                'reflection': f'Как качество {rashi_ru_desc} формирует то, как вы выражаете {gd["principle_ru"]}?',
            },
            'advanced': {
                'technical': f'{graha_key} in {rashi}: {dignity_en}. Rashi lord: {ruler}. Element: {element}, mode: {mode}.',
                'method': 'Vedic graha-in-rashi: the graha principle expresses through the symbolic field of the rashi. Dignity (exaltation/debilitation/own sign/friendly/inimical) modifies the quality and ease of expression.',
                'caution': 'Graha-in-rashi is one factor among many. Aspects (drishti), house placement (bhava), nakshatra, and dasha period all modify the expression significantly.',
                'constructiveChannel': f'Channel the principle of {gd["principle_en"]} through the constructive qualities of {rashi_en}: {rashi_en}.',
            },
            'advancedRu': {
                'technical': f'{gd["ru"]} в {rashi_ru}: {dignity_ru}. Господин раши: {GRAHAS.get(ruler, {}).get("ru", ruler)}. Стихия: {element}, модус: {mode}.',
                'method': 'Ведическая граха-в-раши: принцип грахи выражается через символическое поле раши. Достоинство (экзальтация/падение/своя обитель/дружественный/враждебный знак) изменяет качество и лёгкость выражения.',
                'caution': 'Граха-в-раши — один фактор среди многих. Аспекты (дришти), положение в бхаве, накшатра и период дашы существенно изменяют выражение.',
                'constructiveChannel': f'Направить принцип {gd["principle_ru"]} через конструктивные качества {rashi_ru}: {rashi_ru_desc}.',
            },
            'confidence': 'medium',
        }
        rules.append(rule)

print(f'Generated {len(rules)} vedic rashi rules')
json.dump(rules, open(OUT_FILE, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
print('Saved', OUT_FILE)

# Add knowledge graph nodes
new_nodes = []
for r in rules:
    if r['id'] not in existing_nodes:
        g = r['factor']['graha']
        rs = r['factor']['rashi']
        new_nodes.append(json.dumps({
            'id': r['id'], 'type': 'rule',
            'label': f'{GRAHAS[g]["ru"]} в {next(rd[1] for rd in RASHIS if rd[0]==rs)}',
            'system': 'vedic', 'status': 'draft'
        }, ensure_ascii=False) + '\n')

with open(NODES_FILE, 'a', encoding='utf-8') as f:
    f.writelines(new_nodes)
print(f'Added {len(new_nodes)} nodes')
print('Done.')
